spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.example.demo.config.SnakeCaseNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect